// Enhanced mock data showcasing universal product system
export const mockOfferings = [
  {
    id: 'OFFER-001',
    name: 'Banff National Park Bus Tour',
    description: 'Full day guided tour of Banff National Park with wildlife viewing',
    type: 'seat',
    price: 89,
    currency: 'CAD',
    duration: '8 hours',
    capacity: 24,
    location: 'Banff, AB',
    image: '/images/banff-trip.jpg',
    status: 'active',
    bookings: 145,
    revenue: 12905,
    rating: 4.8,
    instances: 12,
    lastModified: '2024-01-15',
    features: ['WiFi', 'Lunch Included', 'Professional Guide', 'Photo Stops'],
    tags: ['Popular', 'Wildlife', 'Scenic']
  },
  {
    id: 'OFFER-002',
    name: 'Lake Louise Boat Cruise',
    description: 'Scenic boat cruise on the stunning Lake Louise',
    type: 'capacity',
    price: 125,
    currency: 'CAD',
    duration: '6 hours',
    capacity: 30,
    location: 'Lake Louise, AB',
    image: '/images/lake-louise.jpg',
    status: 'active',
    bookings: 89,
    revenue: 11125,
    rating: 4.9,
    instances: 8,
    lastModified: '2024-01-18',
    features: ['Boat Tour', 'Refreshments', 'Photography', 'Small Group'],
    tags: ['Premium', 'Photography', 'Lake']
  },
  {
    id: 'OFFER-003',
    name: 'Vancouver Food Walking Tour',
    description: 'Explore Vancouver\'s culinary scene on foot',
    type: 'open',
    price: 45,
    currency: 'CAD',
    duration: '3 hours',
    capacity: null, // unlimited for open type
    location: 'Vancouver, BC',
    image: '/images/vancouver-food.jpg',
    status: 'active',
    bookings: 67,
    revenue: 3015,
    rating: 4.7,
    instances: 20,
    lastModified: '2024-01-12',
    features: ['Food Tastings', 'Local Guide', 'Walking Tour', 'Cultural Experience'],
    tags: ['Food', 'Cultural', 'Urban']
  },
  {
    id: 'OFFER-004',
    name: 'Mountain Bike Rental',
    description: 'High-quality mountain bike rental with gear',
    type: 'equipment',
    price: 35,
    currency: 'CAD',
    duration: 'Daily',
    capacity: 15, // number of bikes available
    location: 'Whistler, BC',
    image: '/images/bike-rental.jpg',
    status: 'active',
    bookings: 156,
    revenue: 5460,
    rating: 4.6,
    instances: 30,
    lastModified: '2024-01-20',
    features: ['Helmet Included', 'Route Map', 'Maintenance Support', 'Trail Guide'],
    tags: ['Adventure', 'Self-Guided', 'Equipment']
  },
  {
    id: 'OFFER-005',
    name: 'Photography Workshop',
    description: 'Professional landscape photography workshop',
    type: 'timeslot',
    price: 180,
    currency: 'CAD',
    duration: '4 hours',
    capacity: 8,
    location: 'Moraine Lake, AB',
    image: '/images/photography-workshop.jpg',
    status: 'draft',
    bookings: 0,
    revenue: 0,
    rating: null,
    instances: 4,
    lastModified: '2024-01-22',
    features: ['Professional Instructor', 'Equipment Provided', 'Small Group', 'Certificate'],
    tags: ['New', 'Education', 'Photography']
  }
]; 